import { copy, type Lesson } from './data';
export const extraSections = [
  copy('تصميم الكائنات', 'Object design'),
  copy('الأنواع والمجموعات المتقدمة', 'Types & collections'),
  copy('الدوال والسلوك المتقدم', 'Functions & behavior'),
  copy('البيانات والأمان من القيم الفارغة', 'Data & null safety'),
  copy('التزامن والموارد', 'Concurrency & resources'),
  copy('جودة الكود والاختبار', 'Code quality & testing'),
];
type Seed = [string, number, string, string, string, string, string, string, string];
const seeds: Seed[] = [
  [
    'interfaces',
    4,
    'الواجهات والعقود',
    'Interfaces & contracts',
    'تحدد الواجهة السلوك المطلوب دون فرض تفاصيل التنفيذ. يمكن اختبار المستهلك باستبدال التنفيذ.',
    'An interface describes required behavior without choosing its implementation. Consumers can be tested with alternate implementations.',
    'عرّف IGreeter ونفّذ Greeter ليعيد Hello، ثم اطبع النتيجة.',
    'Define IGreeter and implement Greeter to return Hello, then print the result.',
    'Console.WriteLine(new Greeter().Greet());\ninterface IGreeter { string Greet(); }\nclass Greeter : IGreeter { public string Greet() => "Hello"; }',
  ],
  [
    'inheritance',
    4,
    'الوراثة وتعدد الأشكال',
    'Inheritance & polymorphism',
    'تسمح virtual بإعادة تعريف سلوك في نوع مشتق باستخدام override. استخدم الوراثة لعلاقة is-a واضحة.',
    'virtual allows a derived type to override behavior. Reserve inheritance for clear is-a relationships.',
    'اطبع Dog من دالة Speak في نوع مشتق.',
    'Print Dog from a Speak method in a derived type.',
    'Console.WriteLine(new Dog().Speak());\nclass Animal { public virtual string Speak() => "Animal"; }\nclass Dog : Animal { public override string Speak() => "Dog"; }',
  ],
  [
    'records',
    4,
    'السجلات وعدم قابلية التغيير',
    'Records & immutability',
    'تقدّم records مساواة بالقيمة، وwith نسخة بقيم معدلة دون تغيير الأصل.',
    'Records offer value equality; with creates a copy with changed values without mutating the original.',
    'أنشئ Product بقيمة 10 ثم نسخة بسعر 20 واطبع سعر النسخة.',
    'Create Product priced at 10, copy it at 20, and print the new price.',
    'var item = new Product(10m);\nvar updated = item with { Price = 20m };\nConsole.WriteLine(updated.Price);\nrecord Product(decimal Price);',
  ],
  [
    'generics',
    5,
    'الأنواع العامة Generics',
    'Generics',
    'تحافظ الأنواع العامة على سلامة الأنواع مع إعادة استخدام السلوك.',
    'Generics preserve type safety while reusing behavior.',
    'اكتب Identity<T> يعيد مدخله واطبع Identity(42).',
    'Write Identity<T> that returns its input and print Identity(42).',
    'T Identity<T>(T value) => value;\nConsole.WriteLine(Identity(42));',
  ],
  [
    'dictionaries',
    5,
    'القواميس والمفاتيح',
    'Dictionaries & keys',
    'يربط Dictionary مفتاحًا فريدًا بقيمة. استخدم TryGetValue للوصول الذي قد يفشل.',
    'Dictionary maps a unique key to a value. Use TryGetValue when a key may not exist.',
    'خزّن Naser بقيمة 10 ثم اقرأ القيمة واطبعها بأمان.',
    'Store Naser with value 10, read it safely, and print it.',
    'var scores = new Dictionary<string, int> { ["Naser"] = 10 };\nif (scores.TryGetValue("Naser", out int score)) Console.WriteLine(score);',
  ],
  [
    'sets',
    5,
    'المجموعات وإزالة التكرار',
    'Sets & uniqueness',
    'HashSet يحتفظ بعناصر فريدة؛ الإضافة المتكررة لا تغيّر عدد العناصر.',
    'HashSet keeps unique elements; adding a duplicate does not change its count.',
    'أضف 1، 1، 2 إلى HashSet واطبع العدد.',
    'Add 1, 1, 2 to a HashSet and print its count.',
    'var values = new HashSet<int> { 1, 1, 2 };\nConsole.WriteLine(values.Count);',
  ],
  [
    'delegates',
    6,
    'المفوّضات وFunc',
    'Delegates & Func',
    'المفوّض قيمة تشير إلى دالة ذات توقيع محدد. Func يحتوي نوع النتيجة في آخر وسيط نوعي.',
    'A delegate refers to a function with a specific signature. Func places its return type last.',
    'اكتب Func يضاعف العدد واطبع نتيجة 4.',
    'Create a Func that doubles a number and print the result for 4.',
    'Func<int, int> doubleValue = value => value * 2;\nConsole.WriteLine(doubleValue(4));',
  ],
  [
    'closures',
    6,
    'التعبيرات Lambda والإغلاق',
    'Lambdas & closures',
    'يمكن لـLambda التقاط متغير من النطاق الخارجي. انتبه إلى وقت تغيير المتغير الملتقط.',
    'A lambda can capture an outer variable. Be aware of when the captured variable changes.',
    'التقط factor بقيمة 3 واضرب 4 به.',
    'Capture factor with value 3 and multiply 4 by it.',
    'int factor = 3;\nFunc<int, int> multiply = value => value * factor;\nConsole.WriteLine(multiply(4));',
  ],
  [
    'extensions',
    6,
    'دوال الامتداد',
    'Extension methods',
    'تضيف دالة الامتداد صيغة استدعاء مريحة دون تعديل النوع الأصلي. تحفظ في فئة static.',
    'An extension method offers convenient call syntax without modifying the original type. It lives in a static class.',
    'أضف Square للعدد الصحيح واطبع مربع 5.',
    'Add Square to an integer and print the square of 5.',
    'Console.WriteLine(5.Square());\nstatic class NumberExtensions { public static int Square(this int value) => value * value; }',
  ],
  [
    'nullable',
    7,
    'القيم الفارغة وNullable',
    'Null safety & nullable types',
    'استخدم ? للإشارة إلى أن القيمة قد تكون فارغة، و?? لتوفير بديل واضح.',
    'Use ? to declare a potentially absent value and ?? to supply an explicit fallback.',
    'عرّف اسمًا فارغًا واطبع Guest كبديل.',
    'Declare a null name and print Guest as a fallback.',
    'string? name = null;\nConsole.WriteLine(name ?? "Guest");',
  ],
  [
    'patterns',
    7,
    'مطابقة الأنماط',
    'Pattern matching',
    'تعبيرات switch تربط المدخل بنتيجة واضحة. رتّب الأنماط من الخاص إلى العام.',
    'Switch expressions map inputs to results. Order patterns from specific to general.',
    'صنّف العدد 5 إلى Positive باستخدام switch.',
    'Classify 5 as Positive with a switch expression.',
    'int value = 5;\nstring label = value switch { > 0 => "Positive", 0 => "Zero", _ => "Negative" };\nConsole.WriteLine(label);',
  ],
  [
    'json',
    7,
    'التسلسل باستخدام JSON',
    'JSON serialization',
    'System.Text.Json يحول الكائنات إلى تمثيل نصي. اجعل عقود النقل صريحة وقابلة للتغيير المدروس.',
    'System.Text.Json serializes objects into text. Keep transport contracts explicit and evolve them deliberately.',
    'حوّل كائنًا يحمل Value بقيمة 7 إلى JSON.',
    'Serialize an object with Value equal to 7 to JSON.',
    'using System.Text.Json;\nConsole.WriteLine(JsonSerializer.Serialize(new { Value = 7 }));',
  ],
  [
    'cancellation',
    8,
    'إلغاء المهام',
    'Task cancellation',
    'CancellationToken يمثل طلب إلغاء تعاوني. يجب أن يمر عبر سلسلة الاستدعاء.',
    'CancellationToken represents cooperative cancellation and should flow through the call chain.',
    'أنشئ مصدر إلغاء وألغِه ثم اطبع حالة الطلب.',
    'Create and cancel a cancellation source, then print its requested state.',
    'using var source = new CancellationTokenSource();\nsource.Cancel();\nConsole.WriteLine(source.IsCancellationRequested);',
  ],
  [
    'task-all',
    8,
    'تنسيق المهام المتوازية',
    'Coordinating tasks',
    'WhenAll ينتظر مجموعة مهام؛ لا يضمن وحده أنها بدأت على خيوط مستقلة.',
    'WhenAll waits for multiple tasks; it does not itself guarantee separate threads.',
    'انتظر نتيجتي 2 و3 ثم اطبع مجموعهما.',
    'Await results 2 and 3 and print their sum.',
    'var results = await Task.WhenAll(Task.FromResult(2), Task.FromResult(3));\nConsole.WriteLine(results.Sum());',
  ],
  [
    'disposal',
    8,
    'إدارة الموارد وusing',
    'Resource management',
    'using يضمن Dispose عند الخروج من النطاق، حتى عند حدوث استثناء.',
    'using calls Dispose when leaving the scope, including exceptional exits.',
    'استخدم StringReader لقراءة النص Hello ثم اطبعه.',
    'Use StringReader to read Hello and print it.',
    'using var reader = new StringReader("Hello");\nConsole.WriteLine(reader.ReadToEnd());',
  ],
  [
    'validation',
    9,
    'التحقق من المدخلات',
    'Input validation',
    'افصل التحقق من المدخلات عن تنفيذ قواعد العمل. TryParse مناسب لمدخل غير موثوق.',
    'Separate input validation from business logic. TryParse works well for untrusted input.',
    'ارفض النص abc باستخدام TryParse واطبع Invalid.',
    'Reject abc with TryParse and print Invalid.',
    'bool valid = int.TryParse("abc", out _);\nConsole.WriteLine(valid ? "Valid" : "Invalid");',
  ],
  [
    'unit-testing',
    9,
    'تصميم كود قابل للاختبار',
    'Design for testing',
    'الدالة النقية تعتمد على مدخلاتها وتعيد نتيجة دون أثر خارجي، فتسهل تغطية القيم الحدية.',
    'A pure function depends on its inputs and returns a value without external effects, making boundary tests easier.',
    'اكتب IsEven وافحص 2 و3 واطبع Passed إذا تحقق الشرطان.',
    'Write IsEven, check 2 and 3, and print Passed when both assertions hold.',
    'bool IsEven(int value) => value % 2 == 0;\nConsole.WriteLine(IsEven(2) && !IsEven(3) ? "Passed" : "Failed");',
  ],
  [
    'capstone',
    9,
    'المشروع الختامي: تحليل الطلبات',
    'Capstone: order analysis',
    'اجمع الأنواع والمجموعات والاستعلام والدوال في حل صغير واضح يمكن اختباره.',
    'Combine types, collections, queries, and methods in a small testable solution.',
    'رشّح الأسعار الموجبة من 10 و-5 و20 واطبع مجموعها.',
    'Filter positive prices from 10, -5, 20 and print their sum.',
    'decimal[] prices = { 10m, -5m, 20m };\nConsole.WriteLine(prices.Where(price => price > 0).Sum());',
  ],
];
const outputs = [
  'Hello',
  'Dog',
  '20',
  '42',
  '10',
  '2',
  '8',
  '12',
  '25',
  'Guest',
  'Positive',
  '{"Value":7}',
  'True',
  '5',
  'Hello',
  'Invalid',
  'Passed',
  '30',
];
export const extendedLessons: Lesson[] = seeds.map((s, i) => ({
  id: s[0],
  section: s[1],
  title: copy(s[2], s[3]),
  minutes: 25 + (i % 4) * 5,
  explanation: copy(s[4], s[5]),
  task: copy(s[6], s[7]),
  starter: '// ' + s[7] + '\n',
  solution: s[8],
  expected: outputs[i],
  tokens: [s[8].split('\n')[0], 'Console.WriteLine', outputs[i], ';'],
}));
